# Generated by Django 6.0.2 on 2026-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_user_id_task_user_alter_task_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desciption',
            new_name='description',
        ),
    ]
