# Generated by Django 6.0.2 on 2026-03-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_rename_desciption_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Work'), (3, 'Home Improvement')]),
        ),
    ]
