# Generated by Django 6.0.2 on 2026-03-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Priority 0'), (2, 'Priority 1'), (3, 'Priority 2'), (4, 'Priority 3')], default=1),
        ),
    ]
